/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 4548$
 * $Date: 2011-08-01$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		4548
#define SVN_REVSTR	"4548"
#define SVN_REVDATE	"2011-08-01"
#define SVN_REVSTAMP	20110801L
#define SVN_REVMODIFIED	0

#endif /* SVN_REV_H */
